[build]
builder = "nixpacks"
buildCommand = "python -m pip install -r requirements.txt"
provider = ["python"]

[deploy]
startCommand = "python api/app/main.py"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "never"

